"""Added tracker_db_table

Revision ID: 3c409934de50
Revises: dcf644ec6a71
Create Date: 2026-02-22 00:05:12.051515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c409934de50'
down_revision: Union[str, None] = 'dcf644ec6a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_db_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_db_file_file_hash'), 'tracker_db_file', ['file_hash'], unique=False)
    op.create_index(op.f('ix_tracker_db_file_id'), 'tracker_db_file', ['id'], unique=False)
    op.create_index(op.f('ix_tracker_db_file_tenant_id'), 'tracker_db_file', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_db_file_tenant_id'), table_name='tracker_db_file')
    op.drop_index(op.f('ix_tracker_db_file_id'), table_name='tracker_db_file')
    op.drop_index(op.f('ix_tracker_db_file_file_hash'), table_name='tracker_db_file')
    op.drop_table('tracker_db_file')
    # ### end Alembic commands ###
