"""create  encrypted tenant DB configuration  table

Revision ID: 3c5d5f3860a3
Revises: 7d1c2e3f4a5b
Create Date: 2026-08-15 16:00:56.312554

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c5d5f3860a3"
down_revision: Union[str, None] = "7d1c2e3f4a5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "tenant_databases_tenant_id_key", "tenant_databases", type_="unique"
    )
    op.drop_index("ix_tenant_databases_tenant_id", table_name="tenant_databases")
    op.create_index(
        op.f("ix_tenant_databases_tenant_id"),
        "tenant_databases",
        ["tenant_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenant_databases_tenant_id"), table_name="tenant_databases")
    op.create_index(
        "ix_tenant_databases_tenant_id", "tenant_databases", ["tenant_id"], unique=False
    )
    op.create_unique_constraint(
        "tenant_databases_tenant_id_key",
        "tenant_databases",
        ["tenant_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
