"""added CostLog & Runs

Revision ID: 84d6c8d986ec
Revises: 3c409934de50
Create Date: 2026-02-24 03:10:26.100966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d6c8d986ec'
down_revision: Union[str, None] = '3c409934de50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracker_db_file', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_tracker_db_file_tenant_id', table_name='tracker_db_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tracker_db_file_tenant_id', 'tracker_db_file', ['tenant_id'], unique=False)
    op.alter_column('tracker_db_file', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
