import re
from sqlalchemy import text
from app.core.db import get_db_session

class SQLValidator:
    @staticmethod
    def validate_and_enforce_tenant(sql_query: str, tenant_id: str) -> str:
        """
        Validates the SQL query and enforces tenant isolation by adding a WHERE clause for tenant_id.
        
        Args:
            sql_query (str): The original SQL query generated by the agent.
            tenant_id (str): The tenant ID to enforce in the SQL query (UUID string).
            
        Returns:
            str: The validated and tenant-enforced SQL query.
            
        Raises:
            ValueError: If the query contains forbidden operations.
        """
        forbidden_words = ["drop", "delete", "update", "insert", "alter"]

        if any(word in sql_query.lower() for word in forbidden_words):
            raise ValueError("Security Violation: Only SELECT queries allowed.")
        
        # Enforce Tenant Isolation - IMPORTANT: tenant_id is UUID string, must be quoted
        if "where" in sql_query.lower():
            sql = re.sub(
                r"(WHERE)",
                rf"\1 tenant_id = '{tenant_id}' AND ",
                sql_query,
                flags=re.IGNORECASE
            )
        else:
            sql = sql_query + f" WHERE tenant_id = '{tenant_id}'"

        print(f"[SQL_VALIDATOR] Enforced tenant filter. Final SQL: {sql[:200]}...")
        return sql 
    
    @staticmethod
    def get_query_cost(sql: str) -> float:
        """
        Estimates the cost of executing a SQL query using EXPLAIN.
        
        Args:
            sql (str): The SQL query to estimate.
            
        Returns:
            float: The estimated query cost.
        """
        try:
            db = get_db_session()
            plan = db.execute(text(f"EXPLAIN {sql}")).fetchall()
            db.close()
            
            match = re.search(r"cost=[\d.]+\.\.([\d.]+)", str(plan[0]))
            if match:
                return float(match.group(1))
            return 0.0
        except Exception as e:
            print(f"Error getting query cost: {e}")
            return 0.0