import React, { useEffect, useState } from 'react';
import apiService from '../services/apiService';

export default function TenantDatabasePage() {
  const [form, setForm] = useState({ database_type: 'postgresql', host: '', port: 5432, database_name: '', username: '', password: '', default_schema: 'public', ssl_enabled: true, ssl_mode: 'require', connection_timeout: 10 });
  const [status, setStatus] = useState(null);
  const [schema, setSchema] = useState(null);
  const [busy, setBusy] = useState(false);
  const loadStatus = async () => { try { setStatus(await apiService.getTenantDatabaseStatus()); } catch (_) { setStatus({ connected: false }); } };
  useEffect(() => { loadStatus(); }, []);
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { await apiService.connectTenantDatabase({ ...form, port: Number(form.port), connection_timeout: Number(form.connection_timeout) }); setForm({ ...form, password: '' }); await loadStatus(); } catch (error) { alert(error.message || 'Connection failed'); } finally { setBusy(false); } };
  const action = async (type) => { setBusy(true); try { if (type === 'test') alert(JSON.stringify(await apiService.testTenantDatabase())); if (type === 'schema') setSchema(await apiService.getTenantDatabaseSchema(true)); if (type === 'disconnect' && window.confirm('Disconnect this database?')) { await apiService.disconnectTenantDatabase(); setSchema(null); } await loadStatus(); } catch (error) { alert(error.message || 'Database action failed'); } finally { setBusy(false); } };
  return <main className="admin-panel"><div className="admin-header"><h1>Tenant Database</h1><p>Admin-only, read-only external SQL connection.</p></div><div className="tab-content"><div className="send-invitation-form"><form onSubmit={submit}>{['host', 'database_name', 'username'].map((name) => <div className="form-group" key={name}><label>{name.replace('_', ' ')}</label><input required value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} /></div>)}<div className="form-group"><label>Database type</label><select value={form.database_type} onChange={(e) => setForm({ ...form, database_type: e.target.value })}><option value="postgresql">PostgreSQL</option><option value="mysql">MySQL</option></select></div><div className="form-group"><label>Port</label><input type="number" value={form.port} onChange={(e) => setForm({ ...form, port: e.target.value })} /></div><div className="form-group"><label>Password</label><input required type="password" autoComplete="new-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div><button className="btn-primary" disabled={busy}>{busy ? 'Working...' : 'Connect / update'}</button></form></div><div className="invitations-list"><h3>Status</h3><pre>{JSON.stringify(status, null, 2)}</pre><button className="btn-primary" disabled={busy} onClick={() => action('test')}>Test</button>{' '}<button className="btn-primary" disabled={busy} onClick={() => action('schema')}>Refresh schema</button>{' '}<button className="btn-danger" disabled={busy} onClick={() => action('disconnect')}>Disconnect</button>{schema && <><h3>Table relationships</h3>{schema.relationships?.length ? <ul>{schema.relationships.map((r, i) => <li key={i}>{r.from_table}.{r.from_columns.join(', ')} → {r.to_table}.{r.to_columns.join(', ')}</li>)}</ul> : <p>No foreign-key relationships found.</p>}<pre>{JSON.stringify(schema, null, 2)}</pre></>}</div></div></main>;
}
