"""Shared question-type classification — single source of truth.

Previously this module maintained its own keyword lists that could contradict
the production router's ``calculate_deterministic_route()`` patterns, leading
to thought-node tool-selection hints that disagreed with the routing decision
already made upstream.

Now ``classify_question_type`` delegates to the same deterministic route
calculator used by the router, mapping its output to ``"data"`` / ``"knowledge"``.
The legacy keyword lists are kept only as a tiebreaker for ambiguous routes
(COMPLEX / DIRECT_QA / GREETING) where the router does not emit a clear
SQL-vs-retrieval signal.
"""

from __future__ import annotations

# Legacy keyword sets — used only as a fallback tiebreaker for ambiguous routes.
# Legacy keyword sets — used only as a fallback tiebreaker for ambiguous routes.
_DATA_KEYWORDS = (
    # English — quantitative / database / business-data intent
    "how many",
    "how much",
    "count",
    "total",
    "sum",
    "average",
    "avg",
    "number of",
    "quantity",
    "amount",
    "revenue",
    "sales",
    "profit",
    "cost",
    "price",
    "statistics",
    "stats",
    "database",
    "records",
    "rows",
    "transactions",
    "orders",
    "customers",
    "users",
    "products",
    "growth",
    "percentage",
    "percent",
    "ratio",
    "maximum",
    "minimum",
    "highest",
    "lowest",
    "most",
    "least",
    "top",
    "bottom",
    "per month",
    "per day",
    "per year",
    "by month",
    "by day",
    "by year",
    "monthly",
    "daily",
    "yearly",
    "between",
    "from",
    "to",
    # Arabic — MSA quantitative / database intent
    "كم",
    "كام",
    "عدد",
    "عددهم",
    "كم عدد",
    "كمية",
    "مقدار",
    "مجموع",
    "إجمالي",
    "اجمالي",
    "مجموعهم",
    "إجماليهم",
    "متوسط",
    "المتوسط",
    "نسبة",
    "نسبه",
    "إحصائيات",
    "احصائيات",
    "بيانات",
    "قاعدة البيانات",
    "سجلات",
    "صفوف",
    "طلبات",
    "عملاء",
    "مستخدمين",
    "منتجات",
    "مبيعات",
    "إيرادات",
    "ارباح",
    "أرباح",
    "تكلفة",
    "سعر",
    "أعلى",
    "اكبر",
    "أكبر",
    "أقل",
    "اصغر",
    "أصغر",
    "الأكثر",
    "الاكثر",
    "الأقل",
    "الاقل",
    "ترتيب",
    "نمو",
    "نسبة النمو",
    # Egyptian Arabic — common conversational data questions
    "كام واحد",
    "كام واحدة",
    "كام شخص",
    "كام عميل",
    "كام مستخدم",
    "كام طلب",
    "كام أوردر",
    "كام اوردر",
    "كام منتج",
    "كام جنيه",
    "كام فلوس",
    "كام مرة",
    "عددهم كام",
    "عددها كام",
    "عددهم قد ايه",
    "عددها قد ايه",
    "قد ايه",
    "قد إيه",
    "إجمالي كام",
    "اجمالي كام",
    "المجموع كام",
    "المتوسط كام",
    "متوسط كام",
    "المبيعات كام",
    "الإيرادات كام",
    "الايرادات كام",
    "الأرباح كام",
    "الارباح كام",
    "التكلفة كام",
    "السعر كام",
    "النسبة كام",
    "النسبة قد ايه",
    "أعلى كام",
    "أقل كام",
    "أكتر كام",
    "اكتر كام",
    "أكبر كام",
    "أصغر كام",
    "اكتر واحد",
    "أكتر واحد",
    "أكتر ناس",
    "أعلى منتج",
    "أعلى عميل",
    "أكتر عميل",
    "أكتر منتج",
    "أكتر طلبات",
    "قولي العدد",
    "قولي عدد",
    "قولي الإجمالي",
    "قولي اجمالي",
    "قولي المتوسط",
    "قولي المبيعات",
    "عايز العدد",
    "عايز عدد",
    "عايز أعرف العدد",
    "عايز اعرف العدد",
    "عايز أعرف الإجمالي",
    "عايز اعرف الاجمالي",
    "عايز أعرف المتوسط",
    "عايز اعرف المتوسط",
    "وريني العدد",
    "وريني الإجمالي",
    "وريني اجمالي",
    "وريني المتوسط",
    "احسبلي",
    "احسب لي",
    "احسب",
    "احسبلي عدد",
    "احسبلي إجمالي",
    "احسبلي المتوسط",
    "احسبلي المبيعات",
    "احسبلي الأرباح",
    "هات العدد",
    "هات الإجمالي",
    "هات المتوسط",
    "هات المبيعات",
    "طلعلي العدد",
    "طلعلي الإجمالي",
    "طلعلي المتوسط",
    "عايز كام",
    "محتاج أعرف كام",
    "محتاج اعرف كام",
    "فيه كام",
    "في كام",
    "عندي كام",
    "عندنا كام",
)

_KNOWLEDGE_KEYWORDS = (
    # English — explanatory / knowledge intent
    "what is",
    "what are",
    "explain",
    "describe",
    "how does",
    "how do",
    "why",
    "definition",
    "information",
    "policy",
    "meaning",
    "concept",
    "overview",
    "documentation",
    "guide",
    "tutorial",
    "difference",
    "compare",
    "comparison",
    "purpose",
    "reason",
    "architecture",
    "process",
    "procedure",
    "rule",
    "rules",
    "requirement",
    "requirements",
    "how to",
    "what does",
    "tell me about",
    "can you explain",
    # Arabic — MSA knowledge intent
    "ما هو",
    "ما هي",
    "ما معنى",
    "ما المقصود",
    "اشرح",
    "شرح",
    "وضح",
    "توضيح",
    "وصف",
    "لماذا",
    "ليه",
    "تعريف",
    "معلومات",
    "سياسة",
    "مفهوم",
    "فكرة",
    "الفرق بين",
    "قارن",
    "مقارنة",
    "الغرض من",
    "سبب",
    "أهمية",
    "كيفية",
    "كيف يتم",
    "طريقة",
    "خطوات",
    "إجراءات",
    "قواعد",
    "متطلبات",
    "معنى",
    # Egyptian Arabic — conversational knowledge questions
    "يعني ايه",
    "يعني إيه",
    "يعني ايه الكلام ده",
    "يعني إيه الكلام ده",
    "ايه هو",
    "إيه هو",
    "ايه هي",
    "إيه هي",
    "ايه معنى",
    "إيه معنى",
    "المقصود ايه",
    "المقصود إيه",
    "ممكن تشرح",
    "ممكن تشرحلي",
    "ممكن تشرح لي",
    "اشرحلي",
    "اشرح لي",
    "وضحلي",
    "وضح لي",
    "فهمني",
    "فهمني يعني ايه",
    "ممكن توضح",
    "ممكن توضحلي",
    "ليه",
    "ليه كده",
    "ازاي",
    "إزاي",
    "ازاي بيشتغل",
    "إزاي بيشتغل",
    "ازاي بتشتغل",
    "إزاي بتشتغل",
    "بيشتغل ازاي",
    "بيشتغل إزاي",
    "بتشتغل ازاي",
    "بتشتغل إزاي",
    "ايه الفرق",
    "إيه الفرق",
    "الفرق ايه",
    "الفرق إيه",
    "قولي عن",
    "قوللي عن",
    "احكيلي عن",
    "ممكن أعرف",
    "ممكن اعرف",
    "عايز أعرف",
    "عايز اعرف",
    "محتاج أعرف",
    "محتاج اعرف",
    "عايز أفهم",
    "عايز افهم",
    "فهمني الموضوع",
    "اشرح الموضوع",
    "اشرحلي الموضوع",
    "إيه فايدته",
    "ايه فايدته",
    "بيستخدم في ايه",
    "بيستخدم في إيه",
    "بيعمل ايه",
    "بيعمل إيه",
    "بتعمل ايه",
    "بتعمل إيه",
    "بيشتغل ليه",
    "ليه بنستخدم",
    "ليه بنعمل",
    "ازاي نستخدم",
    "إزاي نستخدم",
    "طريقة استخدام",
    "أستخدمه ازاي",
    "استخدمه ازاي",
)

# Router routes that unambiguously signal SQL intent.
_SQL_ROUTES = {"OBVIOUS_SQL", "SIMPLE_SQL"}
# Router routes that unambiguously signal retrieval/knowledge intent.
_RETRIEVAL_ROUTES = {"OBVIOUS_RETRIEVAL", "SIMPLE_RETRIEVAL"}


def classify_question_type(question: str) -> str:
    """
    Return ``"data"`` (SQL) or ``"knowledge"`` (retrieval) for *question*.

    Delegates to the production router's deterministic classifier so the
    thought-node's tool-selection hint is always consistent with the routing
    decision already made upstream.  Falls back to keyword scoring for
    ambiguous routes.
    """
    from app.agent.core.intent_regex_pattern import calculate_deterministic_route

    route = calculate_deterministic_route(question)

    if route in _SQL_ROUTES:
        return "data"
    if route in _RETRIEVAL_ROUTES:
        return "knowledge"

    # Ambiguous route (COMPLEX, DIRECT_QA, GREETING, UNKNOWN) —
    # use keyword scoring as a tiebreaker.
    q = question.lower()
    data_score = sum(kw in q for kw in _DATA_KEYWORDS)
    knowledge_score = sum(kw in q for kw in _KNOWLEDGE_KEYWORDS)
    return "data" if data_score > knowledge_score else "knowledge"


def asks_for_db_data(question: str) -> bool:
    """Return True if the question is most likely answered by a SQL query."""
    return classify_question_type(question) == "data"
