from typing import TypedDict, Optional, List

class AgentState(TypedDict):
    """Represents the state of an agent."""
    '''
    This defines the main state structure of the agent using TypedDict.
    It behaves like a dictionary but with a fixed schema and explicit types.
    The goal is to keep all agent data organized during execution.
    '''

    question: str
    """The question or task that the agent is currently working on."""
    '''
    This represents the current question the agent is processing.
    It can be the original query or a sub-question after decomposition.
    Example: "What is the total sales for last month?"
    '''

    tenant_id: str
    """The tenant ID associated with the agent."""
    '''
    Identifies which tenant (user/company) the agent is working for.
    Important for multi-tenant systems to ensure data isolation.
    Example: "company_123"
    '''

    thought: Optional[str]
    """The current thought or reasoning process of the agent."""
    '''
    Stores the latest reasoning step of the agent.
    Reflects what the agent is currently thinking before taking an action.
    Example: "I need to query the database to get sales data"
    '''

    thoughts: List[str]
    """List of all thoughts from the agent during execution."""
    '''
    Keeps a history of all reasoning steps.
    Useful for debugging, tracing, and explainability.
    Difference:
    - thought → latest reasoning
    - thoughts → full reasoning history
    '''

    last_action: Optional[str]
    """The last action taken by the agent: 'sql', 'retrieval', or 'finish'."""
    '''
    Represents the last decision made by the agent.
    Possible values:
    - "sql" → execute a database query
    - "retrieval" → perform document retrieval (RAG)
    - "finish" → stop and return the final answer
    '''

    observation: Optional[str]
    """The observations or feedback from the last action."""
    '''
    Contains the result or feedback from the last action.
    Example: "Query returned 150 rows"
    '''

    observation_history: List[str]
    """History of all observations from all actions taken."""
    '''
    Stores all past observations.
    Helps the agent avoid repeating actions and improve reasoning.
    '''

    last_sql: Optional[str]
    """The last SQL query generated by the agent, if applicable."""
    '''
    Stores the last generated SQL query.
    Example:
    SELECT SUM(sales) FROM orders WHERE date > '2025-01-01'
    '''

    sql_result: Optional[str]
    """The result obtained from executing the SQL query."""
    '''
    Contains the result of executing the SQL query.
    Example: "Total sales = 50000"
    '''

    retrieval_context: Optional[str]
    """The results obtained from the retrieval process."""
    '''
    Stores context retrieved from external sources like vector DBs or documents.
    Used in Retrieval-Augmented Generation (RAG).
    Example: "Company policy states that..."
    '''

    step_count: int
    """The number of steps taken by the agent in the current task."""
    '''
    Counts how many steps the agent has taken.
    Used to prevent infinite loops and control execution limits.
    '''

    total_cost: float
    """Total cost accumulated during agent execution."""
    '''
    Tracks total LLM usage cost.
    Important for monitoring and controlling budget in production.
    Example: 0.023
    '''

    final_answer: Optional[str]
    """The final answer provided by the agent."""
    '''
    The final output returned to the user.
    Example: "Total sales for last month is 50,000 EGP"
    '''

    # --- Question Decomposition State ---
    '''
    This section handles breaking down complex questions into smaller parts.
    '''

    original_question: Optional[str]
    """The original full question asked by the user."""
    '''
    Stores the original query before decomposition.
    Example: "What are total sales and top products?"
    '''

    sub_questions: List[str]
    """List of decomposed sub-questions, or just the original question if not compound."""
    '''
    Contains smaller questions derived from the original query.
    Example:
    [
        "What are total sales?",
        "What are top products?"
    ]
    '''

    sub_answers: List[str]
    """List of answers collected for each sub-question."""
    '''
    Stores answers for each sub-question.
    Example:
    [
        "Total sales = 50k",
        "Top product = iPhone"
    ]
    '''

    current_sub_question_index: int
    """Index of the currently active sub-question being processed."""
    '''
    Indicates which sub-question is currently being processed.
    Example: 1 → processing the second sub-question
    '''