from typing import TypedDict, Optional, List

class AgentState(TypedDict):
    """Represents the state of an agent."""
    
    question: str
    """The question or task that the agent is currently working on."""

    tenant_id: int
    """The tenant ID associated with the agent."""

    thought: Optional[str]
    """The current thought or reasoning process of the agent."""

    last_action: Optional[str]
    """The last action taken by the agent: 'sql', 'retrieval', or 'finish'."""

    observation: Optional[str]
    """The observations or feedback from the last action."""

    observation_history: List[str]
    """History of all observations from all actions taken."""

    last_sql: Optional[str]
    """The last SQL query generated by the agent, if applicable."""

    retrieval_context: Optional[str]
    """The results obtained from the retrieval process."""

    sql_result: Optional[str]
    """The result obtained from executing the SQL query."""

    step_count: int
    """The number of steps taken by the agent in the current task."""   

    total_cost: float
    """Total cost accumulated during agent execution."""

    thoughts: List[str]
    """List of all thoughts from the agent during execution."""

    final_answer: Optional[str]
    """The final answer provided by the agent."""